# Modelado con Machine Learning

## 1. Objetivo de la etapa
Desarrollar y evaluar modelos de Machine Learning supervisados para predecir el precio de las propiedades, evaluando y validando el mismo a partir de metricas, como asi tambien comparando distintos algoritmos y seleccionando el que presente mejor desempeño.

## 2. Importacion de librerias y carga del dataset procesado

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,root_mean_squared_error, r2_score

import sys
sys.path.append("..")

In [3]:
df = pd.read_csv('../data/processed/listings_processed.csv')

df.shape

(23491, 94)

In [4]:
df.head()

,price,accommodates,bedrooms,bathrooms,latitude,longitude,number_of_reviews,reviews_per_month,review_scores_rating,minimum_nights,...,neighbourhood_cleansed_Villa Gral. Mitre,neighbourhood_cleansed_Villa Lugano,neighbourhood_cleansed_Villa Luro,neighbourhood_cleansed_Villa Ortuzar,neighbourhood_cleansed_Villa Pueyrredon,neighbourhood_cleansed_Villa Real,neighbourhood_cleansed_Villa Riachuelo,neighbourhood_cleansed_Villa Santa Rita,neighbourhood_cleansed_Villa Soldati,neighbourhood_cleansed_Villa Urquiza
0,3983.0,2,1,1,-34.58184,-58.42415,26,0.27,95.0,2,...,False,False,False,False,False,False,False,False,False,False
1,1593.0,1,1,1,-34.59761,-58.39468,20,0.16,95.0,1,...,False,False,False,False,False,False,False,False,False,False
2,2987.0,2,1,1,-34.59382,-58.42994,1,0.06,100.0,1,...,False,False,False,False,False,False,False,False,False,False
3,2987.0,2,1,1,-34.59398,-58.42853,0,0.00,0.0,1,...,False,False,False,False,False,False,False,False,False,False
4,2987.0,2,1,1,-34.59348,-58.42949,66,1.89,99.0,1,...,False,False,False,False,False,False,False,False,False,False

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23491 entries, 0 to 23490
Data columns (total 94 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   price                                     23491 non-null  float64
 1   accommodates                              23491 non-null  int64
 2   bedrooms                                  23491 non-null  int64
 3   bathrooms                                 23491 non-null  int64
 4   latitude                                  23491 non-null  float64
 5   longitude                                 23491 non-null  float64
 6   number_of_reviews                         23491 non-null  int64
 7   reviews_per_month                         23491 non-null  float64
 8   review_scores_rating                      23491 non-null  float64
 9   minimum_nights                            23491 non-null  int64
 10  availability_365                          23491 non-null  int64
 11  room_type_Hotel room                      23491 non-null  bool
 12  room_type_Private room                    23491 non-null  bool
 13  room_type_Shared room                     23491 non-null  bool
 14  property_type_Apartment                   23491 non-null  bool
 15  property_type_Bed and breakfast           23491 non-null  bool
 16  property_type_Boat                        23491 non-null  bool
 17  property_type_Boutique hotel              23491 non-null  bool
 18  property_type_Bungalow                    23491 non-null  bool
 19  property_type_Cabin                       23491 non-null  bool
 20  property_type_Camper/RV                   23491 non-null  bool
 21  property_type_Campsite                    23491 non-null  bool
 22  property_type_Car                         23491 non-null  bool
 23  property_type_Casa particular (Cuba)      23491 non-null  bool
 24  property_type_Castle                      23491 non-null  bool
 25  property_type_Chalet                      23491 non-null  bool
 26  property_type_Condominium                 23491 non-null  bool
 27  property_type_Cottage                     23491 non-null  bool
 28  property_type_Dome house                  23491 non-null  bool
 29  property_type_Dorm                        23491 non-null  bool
 30  property_type_Earth house                 23491 non-null  bool
 31  property_type_Farm stay                   23491 non-null  bool
 32  property_type_Guest suite                 23491 non-null  bool
 33  property_type_Guesthouse                  23491 non-null  bool
 34  property_type_Hostel                      23491 non-null  bool
 35  property_type_Hotel                       23491 non-null  bool
 36  property_type_House                       23491 non-null  bool
 37  property_type_In-law                      23491 non-null  bool
 38  property_type_Loft                        23491 non-null  bool
 39  property_type_Other                       23491 non-null  bool
 40  property_type_Pension (South Korea)       23491 non-null  bool
 41  property_type_Resort                      23491 non-null  bool
 42  property_type_Serviced apartment          23491 non-null  bool
 43  property_type_Tent                        23491 non-null  bool
 44  property_type_Tiny house                  23491 non-null  bool
 45  property_type_Townhouse                   23491 non-null  bool
 46  property_type_Villa                       23491 non-null  bool
 47  neighbourhood_cleansed_Almagro            23491 non-null  bool
 48  neighbourhood_cleansed_Balvanera          23491 non-null  bool
 49  neighbourhood_cleansed_Barracas           23491 non-null  bool
 50  neighbourhood_cleansed_Belgrano           23491 non-null  bool
 51  neighbourhood_cleansed_Boca               23491 non-null  bool
 52  neighbourhood_cleansed_Boedo              23491 non-null  bool
 53  neighbourhood_cleansed_Caballito          23491 non-null  bool
 54  neighbourhood_cleansed_Chacarita          23491 non-null  bool
 55  neighbourhood_cleansed_Coghlan            23491 non-null  bool
 56  neighbourhood_cleansed_Colegiales         23491 non-null  bool
 57  neighbourhood_cleansed_Constitucion       23491 non-null  bool
 58  neighbourhood_cleansed_Flores             23491 non-null  bool
 59  neighbourhood_cleansed_Floresta           23491 non-null  bool
 60  neighbourhood_cleansed_Liniers            23491 non-null  bool
 61  neighbourhood_cleansed_Mataderos          23491 non-null  bool
 62  neighbourhood_cleansed_Monserrat          23491 non-null  bool
 63  neighbourhood_cleansed_Monte Castro       23491 non-null  bool
 64  neighbourhood_cleansed_Nueva Pompeya      23491 non-null  bool
 65  neighbourhood_cleansed_Nuñez              23491 non-null  bool
 66  neighbourhood_cleansed_Palermo            23491 non-null  bool
 67  neighbourhood_cleansed_Parque Avellaneda  23491 non-null  bool
 68  neighbourhood_cleansed_Parque Chacabuco   23491 non-null  bool
 69  neighbourhood_cleansed_Parque Chas        23491 non-null  bool
 70  neighbourhood_cleansed_Parque Patricios   23491 non-null  bool
 71  neighbourhood_cleansed_Paternal           23491 non-null  bool
 72  neighbourhood_cleansed_Puerto Madero      23491 non-null  bool
 73  neighbourhood_cleansed_Recoleta           23491 non-null  bool
 74  neighbourhood_cleansed_Retiro             23491 non-null  bool
 75  neighbourhood_cleansed_Saavedra           23491 non-null  bool
 76  neighbourhood_cleansed_San Cristobal      23491 non-null  bool
 77  neighbourhood_cleansed_San Nicolas        23491 non-null  bool
 78  neighbourhood_cleansed_San Telmo          23491 non-null  bool
 79  neighbourhood_cleansed_Velez Sarsfield    23491 non-null  bool
 80  neighbourhood_cleansed_Versalles          23491 non-null  bool
 81  neighbourhood_cleansed_Villa Crespo       23491 non-null  bool
 82  neighbourhood_cleansed_Villa Del Parque   23491 non-null  bool
 83  neighbourhood_cleansed_Villa Devoto       23491 non-null  bool
 84  neighbourhood_cleansed_Villa Gral. Mitre  23491 non-null  bool
 85  neighbourhood_cleansed_Villa Lugano       23491 non-null  bool
 86  neighbourhood_cleansed_Villa Luro         23491 non-null  bool
 87  neighbourhood_cleansed_Villa Ortuzar      23491 non-null  bool
 88  neighbourhood_cleansed_Villa Pueyrredon   23491 non-null  bool
 89  neighbourhood_cleansed_Villa Real         23491 non-null  bool
 90  neighbourhood_cleansed_Villa Riachuelo    23491 non-null  bool
 91  neighbourhood_cleansed_Villa Santa Rita   23491 non-null  bool
 92  neighbourhood_cleansed_Villa Soldati      23491 non-null  bool
 93  neighbourhood_cleansed_Villa Urquiza      23491 non-null  bool
dtypes: bool(83), float64(5), int64(6)
memory usage: 3.8 MB

## 3. Definicion del problema de modelado

In [6]:
X = df.drop(columns=['price'])  #Features
y = df['price']  #Variable objetivo

In [7]:
X.shape, y.shape

((23491, 93), (23491,))

## 4. Division del dataset en entrenamiento y prueba

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [9]:
X_train.shape, y_train.shape

((18792, 93), (18792,))

## 5. Modelo base: Regresion Lineal

In [10]:
from src.modeling.linear_regression import train_linear_regression

linreg_model = train_linear_regression(X_train, y_train)

In [11]:
y_pred = linreg_model.predict(X_test)

## 6. Evaluacion del modelo

In [12]:
mae_lr = mean_absolute_error(y_test, y_pred)
rmse_lr = root_mean_squared_error(y_test, y_pred)
r2_lr = r2_score(y_test, y_pred)

print(f"MAE: {mae_lr:.2f}")
print(f"RMSE: {rmse_lr:.2f}")
print(f"R2: {r2_lr:.4f}")

MAE: 1313.54
RMSE: 2261.10
R2: 0.3024

El modelo de regresión lineal explica aproximadamente el 28% de la variabilidad del precio,presentando un error promedio absoluto cercano a 1300 unidades.
Estos resultados sirven como referencia para evaluar modelos más complejos.

## 7. Segundo modelo: Arbol de Decision

### 7.1 Entrenamiento

In [13]:
from src.modeling.decision_tree import train_decision_tree

dt_model = train_decision_tree(X_train, y_train)

### 7.2 Prediccion

In [14]:
y_pred_dt = dt_model.predict(X_test)

### 7.3 Evaluacion

In [15]:
mae_dt = mean_absolute_error(y_test, y_pred_dt)
rmse_dt = root_mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print(f"MAE Decision Tree: {mae_dt:.2f}")
print(f"RMSE Decision Tree: {rmse_dt:.2f}")
print(f"R2 Decision Tree: {r2_dt:.4f}")

MAE Decision Tree: 1223.32
RMSE Decision Tree: 2143.58
R2 Decision Tree: 0.3730

### 7.4 Comparacion con el modelo base

In [16]:
results = pd.DataFrame({
    'Model': ['Linear Regression', 'Decision Tree'],
    'MAE': [mae_lr, mae_dt],
    'RMSE': [rmse_lr, rmse_dt],
    'R2': [r2_lr, r2_dt]
})

results

               Model          MAE         RMSE        R2
0  Linear Regression  1313.541818  2261.096622  0.302368
1      Decision Tree  1223.321861  2143.579745  0.373000

Se compara el desempeño del modelo en los conjuntos de entrenamiento y prueba para evaluar posibles signos de sobreajuste.

In [17]:
y_train_pred_dt = dt_model.predict(X_train)

mae_train = mean_absolute_error(y_train, y_train_pred_dt)
rmse_train = np.sqrt(root_mean_squared_error(y_train, y_train_pred_dt))
r2_train = r2_score(y_train, y_train_pred_dt)

print(f'MAE Train Decision Tree: {mae_train: .2f}')
print(f'RMSE Train Decision Tree: {rmse_train:.2f}')
print(f'R2 Train Decision Tree: {r2_train:.4f}')

MAE Train Decision Tree:  1151.56
RMSE Train Decision Tree: 44.90
R2 Train Decision Tree: 0.4788

El Árbol de Decisión mejora el desempeño respecto al modelo base, capturando relaciones no lineales entre las variables.
Sin embargo, su desempeño depende fuertemente de la profundidad del árbol, lo que motiva el uso de modelos ensamblados.

## 8. Tercer modelo: Random Forest

In [18]:
from src.modeling.random_forest import train_random_forest

### 8.1 Entrenamiento

In [19]:
rf_model = train_random_forest(X_train,
                               y_train,
                               {'random_state': 42,
                                'n_estimators': 200, # Numero de árboles en el bosque
                                'max_depth': 12, # Profundidad máxima de cada arbol
                                'min_samples_leaf': 20 , # Minimo de muestras en cada hoja para evitar sobreajuste
                                'n_jobs': -1 # Utiliza todos los núcleos disponibles para acelerar el entrenamiento
                                })

### 8.2 Prediccion

In [20]:
y_pred_rf = rf_model.predict(X_test)

### 8.3 Evaluacion del modelo

In [21]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = root_mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"MAE Random Forest: {mae_rf:.2f}")
print(f"RMSE Random Forest: {rmse_rf:.2f}")
print(f"R2 Random Forest: {r2_rf:.4f}")

MAE Random Forest: 1157.91
RMSE Random Forest: 2057.11
R2 Random Forest: 0.4226

## 9. Cuarto modelo: XGBoost

In [22]:
from src.modeling.xgboost import train_xgboost

### 9.1 Entrenamiento

In [23]:
xgboost = train_xgboost(X_train,y_train)

### 9.2 Prediccion

In [24]:
y_pred_xgb = xgboost.predict(X_test)

### 9.3 Evaluacion del modelo

In [25]:

mae_xgb = mean_absolute_error(y_test, y_pred_xgb)
rmse_xgb = root_mean_squared_error(y_test, y_pred_xgb)
r2_xgb = r2_score(y_test, y_pred_xgb)

print(f"MAE XGBoost: {mae_xgb:.2f}")
print(f"RMSE XGBoost: {rmse_xgb:.2f}")
print(f"R2 XGBoost: {r2_xgb:.4f}")

MAE XGBoost: 1154.71
RMSE XGBoost: 2035.54
R2 XGBoost: 0.4346

### 9.4 Comparacion final de modelos

In [26]:
final_results = pd.DataFrame({
    'Modelo': ["Regresión Lineal", "Árbol de Decisión", "Random Forest", "XGBoost"],
    'MAE': [mae_lr, mae_dt, mae_rf, mae_xgb],
    'RMSE': [rmse_lr, rmse_dt, rmse_rf, rmse_xgb],
    'R2': [r2_lr, r2_dt, r2_rf, r2_xgb]
})

final_results

              Modelo          MAE         RMSE        R2
0   Regresión Lineal  1313.541818  2261.096622  0.302368
1  Árbol de Decisión  1223.321861  2143.579745  0.373000
2      Random Forest  1157.911394  2057.114435  0.422562
3            XGBoost  1154.707443  2035.543582  0.434609

### 9.5 Conclusion de los modelos 

El modelo XGBoost presenta el mejor desempeño entre los modelos evaluados, reduciendo el error y mejorando la capacidad explicativa del precio. Su enfoque de boosting permite capturar relaciones no lineales complejas y optimizar progresivamente los errores residuales, logrando una mejor generalización frente a los modelos basados en arboles individuales.

## 10. Optimizacion de hiperparametros con GridSearchCV

Lo vamos a aplicar a XGBoost para mejorar el mismo.

### 10.1 Definicion del grid

In [27]:
from src.modeling.xgboost_grid import train_model_xgb_grid

param_grid = {
    "n_estimators": [200,400],
    "max_depth": [3, 5, 7],
    "learning_rate": [0.01, 0.05, 0.1],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

### 10.2 Ejecucion del grid

In [28]:
best_xgb, best_params = train_model_xgb_grid(X_train, y_train, param_grid)

Fitting 3 folds for each of 72 candidates, totalling 216 fits

### 10.3 Mejores parametros

In [29]:
print("Mejores hiperparametros encontrados:", best_params)

Mejores hiperparametros encontrados: {'colsample_bytree': 0.8, 'learning_rate': 0.05, 'max_depth': 7, 'n_estimators': 200, 'subsample': 0.8}

## 11. Selecion del modelo final

### 11.1 Evaluacion final en test

In [30]:
y_pred_best_xgb = best_xgb.predict(X_test)

mae_best_xgb = mean_absolute_error(y_test, y_pred_best_xgb)
rmse_best_xgb = root_mean_squared_error(y_test, y_pred_best_xgb)
r2_best_xgb = r2_score(y_test, y_pred_best_xgb)
  
print(f"MAE XGBoost Optimizado: {mae_best_xgb:.2f}")
print(f"RMSE XGBoost Optimizado: {rmse_best_xgb:.2f}")
print(f"R2 XGBoost Optimizado: {r2_best_xgb:.4f}")

MAE XGBoost Optimizado: 1113.84
RMSE XGBoost Optimizado: 1996.62
R2 XGBoost Optimizado: 0.4560

### 11.2 Comparacion final

In [31]:
final_results = pd.DataFrame({
    'Modelo': ["Regresión Lineal", "Árbol de Decisión", "Random Forest", "XGBoost","XGBoost Optimizado"],
    'MAE': [mae_lr, mae_dt, mae_rf, mae_xgb,mae_best_xgb],
    'RMSE': [rmse_lr, rmse_dt, rmse_rf, rmse_xgb,rmse_best_xgb],
    'R2': [r2_lr, r2_dt, r2_rf, r2_xgb,r2_best_xgb]
})

final_results

               Modelo          MAE         RMSE        R2
0    Regresión Lineal  1313.541818  2261.096622  0.302368
1   Árbol de Decisión  1223.321861  2143.579745  0.373000
2       Random Forest  1157.911394  2057.114435  0.422562
3             XGBoost  1154.707443  2035.543582  0.434609
4  XGBoost Optimizado  1113.837583  1996.621023  0.456024

El modelo XGBoost optimizado mediante GridSearchCV presenta el mejor desempeño,logrando una reducción adicional del error y una mejora en la capacidad explicativa del precio.
Este modelo fue seleccionado como modelo final del proyecto.

### 11.3 Guardado de modelo

In [32]:
import joblib

joblib.dump(best_xgb, "../models/xgb_optimizado_v1.pkl")

['../models/xgb_optimizado_v1.pkl']

### 11.4 Guardado de metricas

In [33]:
import json

metrics_etapa3 = {
    "Linear Regression": {
        "R2": r2_lr,
        "MAE": mae_lr,
        "RMSE": rmse_lr
    },
    "Decision Tree": {
        "R2": r2_dt,
        "MAE": mae_dt,
        "RMSE": rmse_dt
    },
    "Random Forest": {
        "R2": r2_rf,
        "MAE": mae_rf,
        "RMSE": rmse_rf
    },
    "XGBoost": {
        "R2": r2_xgb,
        "MAE": mae_xgb,
        "RMSE": rmse_xgb
    },
    "XGBoost Optimizado": {
        "R2": r2_best_xgb,
        "MAE": mae_best_xgb,
        "RMSE": rmse_best_xgb
    }
}

with open("../models/metrics_etapa3.json", "w") as f:
    json.dump(metrics_etapa3, f)

## 12. Carga del modelo y simulacion entorno productivo

### 12.1 Carga del modelo

In [34]:
loaded_model = joblib.load("../models/xgb_optimizado_v1.pkl")

### 12.2 Creacion DataFrame 

Se construye un DataFrame con la misma estructura que los datos utilizados durante el entrenamiento. Esto garantiza que el modelo reciba las variables en el mismo orden y formato, evitando errores derivados de diferencias en las columnas o en el esquema de datos.

In [35]:
nuevo = pd.DataFrame(
    np.zeros((1,len(X_train.columns))),
    columns=X_train.columns
)

### 12.3 Simulacion de input con JSON

In [36]:
json_input = """
{
  "accommodates": 4,
  "bedrooms": 1,
  "bathrooms": 2,
  "number_of_reviews": 100230,
  "reviews_per_month": 10,
  "neighbourhood_cleansed_Boca": 1
}
"""

data = json.loads(json_input)

### 12.4 Asignacion de variables

Se recorren las variables del json y se asignan solo las qe existan en el modelo entrenado, las demas quedan en cero.

In [37]:
for key, value in data.items():
    if key in nuevo.columns:
        nuevo.at[0, key] = value

### 12.5 Prediccion del modelo

In [38]:
precio_estimado = loaded_model.predict(nuevo)

print("Precio estimado Airbnb: ",precio_estimado[0])

Precio estimado Airbnb:  6049.3843

## 13. Pipeline completo para stramlit

In [44]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

### 13.1 Carga dataset original sin dummis

In [79]:
df = pd.read_csv('../data/raw/listings.csv')
df.head()

C:\Users\brian\AppData\Local\Temp\ipykernel_15972\1693856762.py:1: DtypeWarning: Columns (61,62,95) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../data/raw/listings.csv')

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11508,https://www.airbnb.com/rooms/11508,20200426042522,2020-04-26,Amazing Luxurious Apt-Palermo Soho,NaN,LUXURIOUS NEW APT: 1 BDRM- POOL/ GYM/ SPA/ 24-...,LUXURIOUS NEW APT: 1 BDRM- POOL/ GYM/ SPA/ 24-...,none,AREA: PALERMO SOHO Minutes walking distance fr...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.27
1,12463,https://www.airbnb.com/rooms/12463,20200426042522,2020-04-26,Room in Recoleta - awesome location,My apartment is centrally located in Recoleta ...,This is a very comfortable pull-out sofa in th...,My apartment is centrally located in Recoleta ...,none,It's near the school of medicine so the street...,...,f,f,moderate,f,f,1,0,1,0,0.16
2,13095,https://www.airbnb.com/rooms/13095,20200426042522,2020-04-26,Standard Room at Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Standard room : Palermo Viejo Bed & Breakfast ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,0.06
3,13096,https://www.airbnb.com/rooms/13096,20200426042522,2020-04-26,Standard Room in Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Palermo Viejo Bed & Breakfast is located in a ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,NaN
4,13097,https://www.airbnb.com/rooms/13097,20200426042522,2020-04-26,Standard Room at Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Palermo Viejo Bed & Breakfast is located in a ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,1.89

In [80]:
df.shape
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [81]:
cols = [
    'price',
    'accommodates',
    'bedrooms',
    'bathrooms',
    'room_type',
    'property_type',
    'neighbourhood_cleansed',
    'latitude',
    'longitude',
    'number_of_reviews',
    'reviews_per_month',
    'review_scores_rating',
    'minimum_nights',
    'availability_365'
]

In [82]:
df_model = df[cols].copy()

df_model['reviews_per_month'] = df_model['reviews_per_month'].fillna(0)
df_model['review_scores_rating'] = df_model['review_scores_rating'].fillna(0)

df_model['bedrooms'] = df_model['bedrooms'].fillna(df_model['bedrooms'].median())
df_model['bathrooms'] = df_model['bathrooms'].fillna(df_model['bathrooms'].median())

In [83]:
df_model['price'] = df_model['price'].replace('[\$,]', '', regex=True).astype(float)

<>:1: SyntaxWarning: invalid escape sequence '\$'
<>:1: SyntaxWarning: invalid escape sequence '\$'
C:\Users\brian\AppData\Local\Temp\ipykernel_15972\1421263213.py:1: SyntaxWarning: invalid escape sequence '\$'
  df_model['price'] = df_model['price'].replace('[\$,]', '', regex=True).astype(float)

In [84]:
geo_map = df.groupby("neighbourhood_cleansed")[["latitude", "longitude"]].mean()

In [85]:
joblib.dump(geo_map, "../models/geo_map.pkl")

['../models/geo_map.pkl']

In [102]:
price_map = df_model.groupby("neighbourhood_cleansed")["price"].median()

In [103]:
joblib.dump(price_map, "../models/price_map.pkl")

['../models/price_map.pkl']

In [86]:
q99 = df_model['price'].quantile(0.99)
df_model = df_model[df_model['price'] <= q99]

In [87]:
X = df_model.drop(columns="price")
y = df_model["price"]

In [88]:
X = df_model.drop(columns="price")
y = df_model["price"]

In [89]:
categorical_cols = [
    "room_type",
    "property_type",
    "neighbourhood_cleansed"
]

numerical_cols = [col for col in X.columns if col not in categorical_cols]

In [90]:
print("Categóricas:", categorical_cols)
print("Numéricas:", numerical_cols)

Categóricas: ['room_type', 'property_type', 'neighbourhood_cleansed']
Numéricas: ['accommodates', 'bedrooms', 'bathrooms', 'latitude', 'longitude', 'number_of_reviews', 'reviews_per_month', 'review_scores_rating', 'minimum_nights', 'availability_365']

In [91]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [92]:
# Definimos el preprocesador para las columnas categóricas y numéricas
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numerical_cols)
    ]
)

In [93]:
#Transformamos los datos utilizando el preprocesador para verificar que funciona correctamente
X_transformed = preprocessor.fit_transform(X) 
print(X_transformed.shape)

(23491, 96)

In [94]:
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor

In [95]:
# Creamos un pipeline que incluye el preprocesamiento y el modelo XGBoost con los mejores hiperparámetros encontrados
pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", XGBRegressor(**best_params))
])

In [96]:
pipeline.fit(X, y) #Entrenamos el pipeline con los datos originales (sin transformar) ya que el pipeline se encargará de aplicar el preprocesamiento antes de entrenar el modelo.

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['room_type', 'property_type',
                                                   'neighbourhood_cleansed']),
                                                 ('num', 'passthrough',
                                                  ['accommodates', 'bedrooms',
                                                   'bathrooms', 'latitude',
                                                   'longitude',
                                                   'number_of_reviews',
                                                   'reviews_per_month',
                                                   'review_scores_rating',
                                                   'minimum_nights',
                                                   'availability_365'])]...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=7, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [97]:
joblib.dump(pipeline, "../models/xgb_pipeline_v2.pkl")

['../models/xgb_pipeline_v2.pkl']

In [98]:
joblib.dump(geo_map, "../models/geo_map.pkl")

['../models/geo_map.pkl']